<Project Sdk="Prometheus.MSBuild.Sdk">
  
  <PropertyGroup>
    <ProductName>Shin.Framework.Sandbox</ProductName>
    <StartupObject>CoreSandbox.Program</StartupObject>
    <TargetPlatform>net8.0</TargetPlatform>
    <!--<TargetFramework>net8.0-windows10.0.17763.0</TargetFramework>-->
  </PropertyGroup>
  
  <ItemGroup>
      <ProjectReference Include="..\..\packages\Shin.Framework.NetCore\Shin.Framework.NetCore.csproj"
                        PrivateAssets="All" />
      <ProjectReference Include="..\..\packages\Shin.Framework.IoC.DependencyInjection.Ninject.NetCore\Shin.Framework.IoC.DependencyInjection.Ninject.NetCore.csproj"
                        PrivateAssets="All" />
    <!--<ProjectReference Include="..\..\src\Platform\Shin.IoC.DependencyInjection.Ninject.Net8\Shin.IoC.DI.Ninject.Net8.csproj" />-->
  </ItemGroup>

</Project>