<Project>

  <PropertyGroup>
    <SectionSymbol>@</SectionSymbol>
    <LocalNugetRepoDirectory>D:\Users\Bryan\Documents\Projects\HelixTechGroup\local-nuget</LocalNugetRepoDirectory>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <LangVersion>latest</LangVersion>
    <EnableShinFramework>false</EnableShinFramework>
  </PropertyGroup>

  <PropertyGroup>
    <UseGitHub>True</UseGitHub>
    <ProductName>Shin.Framework</ProductName>
    <CompanyName>HelixTechGroup,llc</CompanyName>
    <AuthorName>Bryan M. Longacre</AuthorName>
    <Description>Shin.Framework</Description>
    <CopyrightStartYear>2017</CopyrightStartYear>
    <RepositoryHttpUrl>https://github.com/HelixTechGroup/Shin.Framework.Dotnet</RepositoryHttpUrl>
  </PropertyGroup>
  
</Project>