<Project>
  <!--<PropertyGroup>
    <UseGitHub>True</UseGitHub>
    <ProductName>Shin.Framework</ProductName>
    <CompanyName>HelixTechGroup,llc</CompanyName>
    <AuthorName>Bryan M. Longacre</AuthorName>
    <Description>Shin.Framework</Description>
    <CopyrightStartYear>2017</CopyrightStartYear>
    <RepositoryHttpUrl>https://github.com/HelixTechGroup/Shin.Framework.Dotnet</RepositoryHttpUrl>
  </PropertyGroup>-->
</Project>
