<Project Sdk="Prometheus.MSBuild.Sdk/0.3.1-beta.1">
  <PropertyGroup>
    <SectionSymbol>@</SectionSymbol>
    <!--<TargetPlatform>net10.0</TargetPlatform>-->
    <!--<TargetPlatforms>net6.0;net8.0</TargetPlatforms>
    <EnableShinFramework>false</EnableShinFramework>-->
  </PropertyGroup>
  
  <!--<ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>Shin.Framework.Net8.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>-->
  
  <Import Project="..\..\Shin.Framework\Shin.Framework.projitems" Label="Shared" />
  <!--<ItemGroup>
    <PackageReference Include="Fody" Version="6.8.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="ILMerge.Fody" Version="1.24.0" />
    <PackageReference Include="JetBrainsAnnotations.Fody" Version="2.17.0" />
    <PackageReference Include="NullGuard.Fody" Version="3.1.1" />
  </ItemGroup>-->
</Project>
