<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('$(MSBuildThisFile)', '$(MSBuildThisFileDirectory)../'))" />
  
  <PropertyGroup>
    <SectionSymbol>@</SectionSymbol>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsPackable>false</IsPackable>
    <IsLibraryProject>true</IsLibraryProject>
    <AnalysisMode>AllEnabledByDefault</AnalysisMode>
  </PropertyGroup>

  <!--<PropertyGroup>
    <UseGitHub>True</UseGitHub>
    <ProductName>Shin.Framework</ProductName>
    <CompanyName>HelixTechGroup,llc</CompanyName>
    <AuthorName>Bryan M. Longacre</AuthorName>
    <Description>Shin.Framework</Description>
    <CopyrightStartYear>2017</CopyrightStartYear>
    <RepositoryHttpUrl>https://github.com/HelixTechGroup/Shin.Framework.Dotnet</RepositoryHttpUrl>
  </PropertyGroup>-->
  
  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>$(AssemblyName).MSTest</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
  
  <!--<ItemGroup>
    <PackageReference Include="JetBrains.Annotations" Version="2023.3.0" />
  </ItemGroup>-->
  
  <PropertyGroup Condition="'$(RELEASE)' == 'debug'">
    <MergeBinary>false</MergeBinary>
  </PropertyGroup>
  <!--<PropertyGroup>
    <DefineConstants Condition="'$(DefineConstants)' != ''">$(DefineConstants);JETBRAINS_ANNOTATIONS</DefineConstants>
    <DefineConstants Condition="'$(DefineConstants)' == ''">JETBRAINS_ANNOTATIONS</DefineConstants>
  </PropertyGroup>-->
  <!--<Import Project="..\Shin.Framework\Shin.Framework.projitems" Label="Shared" />-->
</Project>